[2025-03-13T20:39:08.544+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T20:39:08.555+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_FT.parse_job_offerings_task manual__2025-03-13T20:38:51.680143+00:00 [queued]>
[2025-03-13T20:39:08.560+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_FT.parse_job_offerings_task manual__2025-03-13T20:38:51.680143+00:00 [queued]>
[2025-03-13T20:39:08.561+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-13T20:39:08.569+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): parse_job_offerings_task> on 2025-03-13 20:38:51.680143+00:00
[2025-03-13T20:39:08.573+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=140) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T20:39:08.574+0000] {standard_task_runner.py:72} INFO - Started process 142 to run task
[2025-03-13T20:39:08.574+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parse_FT', 'parse_job_offerings_task', 'manual__2025-03-13T20:38:51.680143+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/scraping.py', '--cfg-path', '/tmp/tmp6besqhtk']
[2025-03-13T20:39:08.575+0000] {standard_task_runner.py:105} INFO - Job 75: Subtask parse_job_offerings_task
[2025-03-13T20:39:08.598+0000] {task_command.py:467} INFO - Running <TaskInstance: parse_FT.parse_job_offerings_task manual__2025-03-13T20:38:51.680143+00:00 [running]> on host 0a98252fde59
[2025-03-13T20:39:08.642+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='joel' AIRFLOW_CTX_DAG_ID='parse_FT' AIRFLOW_CTX_TASK_ID='parse_job_offerings_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T20:38:51.680143+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T20:38:51.680143+00:00'
[2025-03-13T20:39:08.643+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-13T20:39:08.643+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-13T20:39:08.643+0000] {logging_mixin.py:190} INFO - Current task name:parse_job_offerings_task state:running start_date:2025-03-13 20:39:08.556215+00:00
[2025-03-13T20:39:08.643+0000] {logging_mixin.py:190} INFO - Dag name:parse_FT and current dag run status:running
[2025-03-13T20:39:08.644+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T20:39:09.097+0000] {warnings.py:112} WARNING - /opt/***/dags/scraping.py:55: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 55 of the file /opt/***/dags/scraping.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(r.text)

[2025-03-13T20:39:09.130+0000] {logging_mixin.py:190} INFO - 3523468
[2025-03-13T20:39:11.424+0000] {logging_mixin.py:190} INFO - 3501064
[2025-03-13T20:39:13.684+0000] {logging_mixin.py:190} INFO - 3495787
[2025-03-13T20:39:15.943+0000] {logging_mixin.py:190} INFO - 3539582
[2025-03-13T20:39:18.181+0000] {logging_mixin.py:190} INFO - 3548387
[2025-03-13T20:39:20.442+0000] {logging_mixin.py:190} INFO - 3504600
[2025-03-13T20:39:22.695+0000] {logging_mixin.py:190} INFO - 3482590
[2025-03-13T20:39:24.962+0000] {logging_mixin.py:190} INFO - 3541336
[2025-03-13T20:39:27.546+0000] {logging_mixin.py:190} INFO - 3545397
[2025-03-13T20:39:29.824+0000] {logging_mixin.py:190} INFO - 3504871
[2025-03-13T20:39:32.077+0000] {logging_mixin.py:190} INFO - 3504839
[2025-03-13T20:39:34.342+0000] {logging_mixin.py:190} INFO - 3504644
[2025-03-13T20:39:36.634+0000] {logging_mixin.py:190} INFO - 3506601
[2025-03-13T20:39:38.932+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping.py", line 101, in parse_job
    to_db(annonce)
  File "/opt/airflow/dags/scraping.py", line 122, in to_db
    cur.execute("""
psycopg2.errors.NotNullViolation: null value in column "requis" of relation "competences" violates not-null constraint
DETAIL:  Failing row contains (1, Français, null).

[2025-03-13T20:39:38.940+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-13T20:39:38.941+0000] {logging_mixin.py:190} INFO - Task start:2025-03-13 20:39:08.556215+00:00 end:2025-03-13 20:39:38.940456+00:00 duration:30.384241
[2025-03-13T20:39:38.941+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): parse_job_offerings_task> dag:<DAG: parse_FT> dagrun:<DagRun parse_FT @ 2025-03-13 20:38:51.680143+00:00: manual__2025-03-13T20:38:51.680143+00:00, state:running, queued_at: 2025-03-13 20:38:51.688234+00:00. externally triggered: True>
[2025-03-13T20:39:38.941+0000] {logging_mixin.py:190} INFO - Failure caused by null value in column "requis" of relation "competences" violates not-null constraint
DETAIL:  Failing row contains (1, Français, null).
[2025-03-13T20:39:38.941+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=parse_FT, task_id=parse_job_offerings_task, run_id=manual__2025-03-13T20:38:51.680143+00:00, execution_date=20250313T203851, start_date=20250313T203908, end_date=20250313T203938
[2025-03-13T20:39:38.958+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T20:39:38.958+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 75 for task parse_job_offerings_task (null value in column "requis" of relation "competences" violates not-null constraint
DETAIL:  Failing row contains (1, Français, null).
; 142)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping.py", line 101, in parse_job
    to_db(annonce)
  File "/opt/airflow/dags/scraping.py", line 122, in to_db
    cur.execute("""
psycopg2.errors.NotNullViolation: null value in column "requis" of relation "competences" violates not-null constraint
DETAIL:  Failing row contains (1, Français, null).

[2025-03-13T20:39:38.981+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-13T20:39:38.994+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T20:39:38.995+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
