[2025-03-13T20:01:38.868+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T20:01:38.880+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_FT.parse_job_offerings_task manual__2025-03-13T20:01:21.038976+00:00 [queued]>
[2025-03-13T20:01:38.885+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_FT.parse_job_offerings_task manual__2025-03-13T20:01:21.038976+00:00 [queued]>
[2025-03-13T20:01:38.886+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-13T20:01:38.894+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): parse_job_offerings_task> on 2025-03-13 20:01:21.038976+00:00
[2025-03-13T20:01:38.899+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=121) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T20:01:38.900+0000] {standard_task_runner.py:72} INFO - Started process 123 to run task
[2025-03-13T20:01:38.900+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parse_FT', 'parse_job_offerings_task', 'manual__2025-03-13T20:01:21.038976+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/scraping.py', '--cfg-path', '/tmp/tmpbic9do58']
[2025-03-13T20:01:38.901+0000] {standard_task_runner.py:105} INFO - Job 52: Subtask parse_job_offerings_task
[2025-03-13T20:01:38.923+0000] {task_command.py:467} INFO - Running <TaskInstance: parse_FT.parse_job_offerings_task manual__2025-03-13T20:01:21.038976+00:00 [running]> on host 4450daee8136
[2025-03-13T20:01:38.968+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='joel' AIRFLOW_CTX_DAG_ID='parse_FT' AIRFLOW_CTX_TASK_ID='parse_job_offerings_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T20:01:21.038976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T20:01:21.038976+00:00'
[2025-03-13T20:01:38.969+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-13T20:01:38.969+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-13T20:01:38.969+0000] {logging_mixin.py:190} INFO - Current task name:parse_job_offerings_task state:running start_date:2025-03-13 20:01:38.880710+00:00
[2025-03-13T20:01:38.970+0000] {logging_mixin.py:190} INFO - Dag name:parse_FT and current dag run status:running
[2025-03-13T20:01:38.970+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T20:01:39.219+0000] {warnings.py:112} WARNING - /opt/***/dags/scraping.py:55: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 55 of the file /opt/***/dags/scraping.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(r.text)

[2025-03-13T20:01:39.272+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping.py", line 101, in parse_job
    to_db(annonce)
  File "/opt/airflow/dags/scraping.py", line 137, in to_db
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "annonces_pkey"
DETAIL:  Key (reference)=(3523468
) already exists.

[2025-03-13T20:01:39.280+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-13T20:01:39.281+0000] {logging_mixin.py:190} INFO - Task start:2025-03-13 20:01:38.880710+00:00 end:2025-03-13 20:01:39.280523+00:00 duration:0.399813
[2025-03-13T20:01:39.281+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): parse_job_offerings_task> dag:<DAG: parse_FT> dagrun:<DagRun parse_FT @ 2025-03-13 20:01:21.038976+00:00: manual__2025-03-13T20:01:21.038976+00:00, state:running, queued_at: 2025-03-13 20:01:21.050671+00:00. externally triggered: True>
[2025-03-13T20:01:39.281+0000] {logging_mixin.py:190} INFO - Failure caused by duplicate key value violates unique constraint "annonces_pkey"
DETAIL:  Key (reference)=(3523468
) already exists.
[2025-03-13T20:01:39.282+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=parse_FT, task_id=parse_job_offerings_task, run_id=manual__2025-03-13T20:01:21.038976+00:00, execution_date=20250313T200121, start_date=20250313T200138, end_date=20250313T200139
[2025-03-13T20:01:39.298+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T20:01:39.299+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 52 for task parse_job_offerings_task (duplicate key value violates unique constraint "annonces_pkey"
DETAIL:  Key (reference)=(3523468
) already exists.
; 123)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping.py", line 101, in parse_job
    to_db(annonce)
  File "/opt/airflow/dags/scraping.py", line 137, in to_db
    cur.execute("""
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "annonces_pkey"
DETAIL:  Key (reference)=(3523468
) already exists.

[2025-03-13T20:01:39.314+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-13T20:01:39.328+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T20:01:39.329+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
