[2025-03-13T16:15:32.794+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-13T16:15:32.803+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_FT.get_daily_listing_task manual__2025-03-13T16:15:31.114480+00:00 [queued]>
[2025-03-13T16:15:32.807+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_FT.get_daily_listing_task manual__2025-03-13T16:15:31.114480+00:00 [queued]>
[2025-03-13T16:15:32.808+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-13T16:15:32.816+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): get_daily_listing_task> on 2025-03-13 16:15:31.114480+00:00
[2025-03-13T16:15:32.820+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=114) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-13T16:15:32.821+0000] {standard_task_runner.py:72} INFO - Started process 116 to run task
[2025-03-13T16:15:32.822+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parse_FT', 'get_daily_listing_task', 'manual__2025-03-13T16:15:31.114480+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/scraping.py', '--cfg-path', '/tmp/tmpkr4lxsd5']
[2025-03-13T16:15:32.822+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask get_daily_listing_task
[2025-03-13T16:15:32.847+0000] {task_command.py:467} INFO - Running <TaskInstance: parse_FT.get_daily_listing_task manual__2025-03-13T16:15:31.114480+00:00 [running]> on host 852d646b8739
[2025-03-13T16:15:32.894+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='joel' AIRFLOW_CTX_DAG_ID='parse_FT' AIRFLOW_CTX_TASK_ID='get_daily_listing_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T16:15:31.114480+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-13T16:15:31.114480+00:00'
[2025-03-13T16:15:32.895+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-13T16:15:32.895+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-13T16:15:32.895+0000] {logging_mixin.py:190} INFO - Current task name:get_daily_listing_task state:running start_date:2025-03-13 16:15:32.803736+00:00
[2025-03-13T16:15:32.896+0000] {logging_mixin.py:190} INFO - Dag name:parse_FT and current dag run status:running
[2025-03-13T16:15:32.896+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-13T16:15:32.896+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping.py", line 173, in get_daily_listing
    with open("/urls.txt", "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/urls.txt'
[2025-03-13T16:15:32.905+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-13T16:15:32.905+0000] {logging_mixin.py:190} INFO - Task start:2025-03-13 16:15:32.803736+00:00 end:2025-03-13 16:15:32.905019+00:00 duration:0.101283
[2025-03-13T16:15:32.905+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_daily_listing_task> dag:<DAG: parse_FT> dagrun:<DagRun parse_FT @ 2025-03-13 16:15:31.114480+00:00: manual__2025-03-13T16:15:31.114480+00:00, state:running, queued_at: 2025-03-13 16:15:31.123062+00:00. externally triggered: True>
[2025-03-13T16:15:32.906+0000] {logging_mixin.py:190} INFO - Failure caused by [Errno 13] Permission denied: '/urls.txt'
[2025-03-13T16:15:32.906+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=parse_FT, task_id=get_daily_listing_task, run_id=manual__2025-03-13T16:15:31.114480+00:00, execution_date=20250313T161531, start_date=20250313T161532, end_date=20250313T161532
[2025-03-13T16:15:32.921+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-13T16:15:32.922+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 10 for task get_daily_listing_task ([Errno 13] Permission denied: '/urls.txt'; 116)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping.py", line 173, in get_daily_listing
    with open("/urls.txt", "w") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/urls.txt'
[2025-03-13T16:15:32.955+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-13T16:15:32.967+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-13T16:15:32.968+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
