[2025-03-14T00:47:57.835+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-14T00:47:57.846+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parse_FT.parse_job_offerings_task scheduled__2025-03-13T00:00:00+00:00 [queued]>
[2025-03-14T00:47:57.852+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parse_FT.parse_job_offerings_task scheduled__2025-03-13T00:00:00+00:00 [queued]>
[2025-03-14T00:47:57.852+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-14T00:47:57.860+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): parse_job_offerings_task> on 2025-03-13 00:00:00+00:00
[2025-03-14T00:47:57.865+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=83) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-14T00:47:57.865+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2025-03-14T00:47:57.866+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'parse_FT', 'parse_job_offerings_task', 'scheduled__2025-03-13T00:00:00+00:00', '--job-id', '87', '--raw', '--subdir', 'DAGS_FOLDER/scraping.py', '--cfg-path', '/tmp/tmptloy4b39']
[2025-03-14T00:47:57.867+0000] {standard_task_runner.py:105} INFO - Job 87: Subtask parse_job_offerings_task
[2025-03-14T00:47:57.891+0000] {task_command.py:467} INFO - Running <TaskInstance: parse_FT.parse_job_offerings_task scheduled__2025-03-13T00:00:00+00:00 [running]> on host fb640e47a740
[2025-03-14T00:47:57.931+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='joel' AIRFLOW_CTX_DAG_ID='parse_FT' AIRFLOW_CTX_TASK_ID='parse_job_offerings_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T00:00:00+00:00'
[2025-03-14T00:47:57.932+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-14T00:47:57.932+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-14T00:47:57.932+0000] {logging_mixin.py:190} INFO - Current task name:parse_job_offerings_task state:running start_date:2025-03-14 00:47:57.847257+00:00
[2025-03-14T00:47:57.932+0000] {logging_mixin.py:190} INFO - Dag name:parse_FT and current dag run status:running
[2025-03-14T00:47:57.933+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-14T00:47:58.170+0000] {warnings.py:112} WARNING - /opt/***/dags/scraping.py:55: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 55 of the file /opt/***/dags/scraping.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  soup = BeautifulSoup(r.text)

[2025-03-14T00:47:58.199+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping.py", line 101, in parse_job
    to_db(annonce)
  File "/opt/airflow/dags/scraping.py", line 129, in to_db
    cur.execute("""
psycopg2.errors.SyntaxError: syntax error at or near "RETURNING"
LINE 45:         RETURNING reference;
                 ^

[2025-03-14T00:47:58.205+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-14T00:47:58.205+0000] {logging_mixin.py:190} INFO - Task start:2025-03-14 00:47:57.847257+00:00 end:2025-03-14 00:47:58.205322+00:00 duration:0.358065
[2025-03-14T00:47:58.206+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): parse_job_offerings_task> dag:<DAG: parse_FT> dagrun:<DagRun parse_FT @ 2025-03-13 00:00:00+00:00: scheduled__2025-03-13T00:00:00+00:00, state:running, queued_at: 2025-03-14 00:47:30.648218+00:00. externally triggered: False>
[2025-03-14T00:47:58.206+0000] {logging_mixin.py:190} INFO - Failure caused by syntax error at or near "RETURNING"
LINE 45:         RETURNING reference;
                 ^
[2025-03-14T00:47:58.206+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=parse_FT, task_id=parse_job_offerings_task, run_id=scheduled__2025-03-13T00:00:00+00:00, execution_date=20250313T000000, start_date=20250314T004757, end_date=20250314T004758
[2025-03-14T00:47:58.221+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-14T00:47:58.221+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 87 for task parse_job_offerings_task (syntax error at or near "RETURNING"
LINE 45:         RETURNING reference;
                 ^
; 85)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scraping.py", line 101, in parse_job
    to_db(annonce)
  File "/opt/airflow/dags/scraping.py", line 129, in to_db
    cur.execute("""
psycopg2.errors.SyntaxError: syntax error at or near "RETURNING"
LINE 45:         RETURNING reference;
                 ^

[2025-03-14T00:47:58.239+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-14T00:47:58.249+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-14T00:47:58.250+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
